In [1]:
from non_local_detector.transitions.discrete import (
    Stationary,
    CategoricalGLM,
    diag_stickiness,
)

import numpy as np

speed = np.array([0.1, 0.2, 0.3, 0.4, 0.5])  # Example speed data
# Stationary “sticky diagonal” example
transition = diag_stickiness([0.95, 0.90, 0.98]) #

# Covariate-dependent GLM example
glm_transition = CategoricalGLM(
    n_states=3,
    formula="1 + bs(speed, df=4)",
    concentration=2.0,
    stickiness=1e3,
).initialize_parameters(
    covariate_data={"speed": speed}
)
glm_transition

CategoricalGLM(n_states=3, n_features=5, formula='1 + bs(speed, df=4)'), concentration=2.0, stickiness=1000.0, l2_penalty=1e-05)

In [2]:
glm_transition.matrix(covariate_data={"speed": speed})

Array([[[0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333]],

       [[0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333]],

       [[0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333]],

       [[0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333]],

       [[0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333],
        [0.3333333, 0.3333333, 0.3333333]]], dtype=float32)

In [3]:
transition.matrix()

array([[0.95 , 0.025, 0.025],
       [0.05 , 0.9  , 0.05 ],
       [0.01 , 0.01 , 0.98 ]])

In [4]:
transition.stickiness

array([0., 0., 0.])